//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TopID { get; set; }
        public Nullable<int> BottomID { get; set; }
        public Nullable<int> ShoesID { get; set; }
        public Nullable<int> AccessoryID { get; set; }
        public Nullable<int> OccasionID { get; set; }
        public string Description { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual Shoe Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}
